export const useSkillsList = () => {
  return [
    { title: "Bootstrap", imgUrl: "img/skills/bootstrap.png" },
    { title: "CSS", imgUrl: "img/skills/css.png" },
    { title: "Docker", imgUrl: "img/skills/docker.png" },
    { title: "Figma", imgUrl: "img/skills/figma.png" },
    { title: "Git", imgUrl: "img/skills/git.png" },
    { title: "HTML", imgUrl: "img/skills/html.png" },
    { title: "Java", imgUrl: "img/skills/java.png" },
    { title: "JavaScript", imgUrl: "img/skills/javascript.png" },
    { title: "Jest", imgUrl: "img/skills/jest.png" },
    { title: "JetBrains", imgUrl: "img/skills/jetbrains.png" },
    { title: "Material UI", imgUrl: "img/skills/mui.png" },
    { title: "MySQL", imgUrl: "img/skills/mysql.png" },
    { title: "Next.js", imgUrl: "img/skills/next.png" },
    { title: "Node.js", imgUrl: "img/skills/nodejs.png" },
    { title: "Office", imgUrl: "img/skills/office.png" },
    { title: "Photoshop", imgUrl: "img/skills/photoshop.png" },
    { title: "PostgreSQL", imgUrl: "img/skills/postgres.png" },
    { title: "Python", imgUrl: "img/skills/python.png" },
    { title: "React", imgUrl: "img/skills/reactjs.png" },
    { title: "Spring Boot", imgUrl: "img/skills/springBoot.png" },
    { title: "Tailwind", imgUrl: "img/skills/tailwind.png" },
    { title: "Three.js", imgUrl: "img/skills/threejs.png" },
    { title: "TypeScript", imgUrl: "img/skills/typescript.png" },
    { title: "Vite", imgUrl: "img/skills/vite.png" },
  ];
};
